# -*- coding: utf-8 -*-
"""Convent_json.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BhObZsnft2C7IG1KAFEGn4olzKhEkSoF
"""

import json
from datetime import datetime

# ฟังก์ชันสำหรับแปลงวันที่
def convert_order_date(order_date):
    # แปลงวันที่จากรูปแบบ "m/d/yy" เป็น datetime
    date_obj = datetime.strptime(order_date, "%m/%d/%y")
    # แปลง datetime เป็นรูปแบบ "yyyy-MM-ddTHH:mm:ss"
    return date_obj.strftime("%Y-%m-%dT%H:%M:%S")

# อ่านไฟล์ JSON
with open('data.json', 'r') as file:
    data = json.load(file)

# ตรวจสอบและแปลง OrderDate สำหรับแต่ละรายการในรายการ
for item in data:
    if "OrderDate" in item:
        original_date = item["OrderDate"]
        converted_date = convert_order_date(original_date)
        item["OrderDate"] = converted_date
        print(f"Converted OrderDate from {original_date} to {converted_date}")

# ถ้าต้องการบันทึกข้อมูลที่แปลงแล้วกลับไปยังไฟล์ JSON
with open('converted_data.json', 'w') as file:
    json.dump(data, file, indent=4)

